#!/usr/bin/env bash

set -e

backupDir=$HOME/.dotfile/backup
pkginfo="$backupDir/pkginfo.md"
scriptPath='$HOME/.dotfile/scripts/pkginfo.sh'

# Create backup directory if it doesn't exist
mkdir -p "$backupDir"

# Add script information to the generated file
echo "This file is automatically generated by: $scriptPath" >"$pkginfo"
echo "Purpose: Describe explicitly installed packages and their descriptions." >>"$pkginfo"
echo "" >>"$pkginfo"

# Add table headers
echo "| 软件包 | 描述 |" >>"$pkginfo"
echo "| ------- | ---- |" >>"$pkginfo"

# Loop through installed packages and populate the table
while read -r package; do
	description=$(LANG=C paru -Qi "$package" | awk -F': ' '/^Description/ {print $2}')
	echo "| $package | $description |" >>"$pkginfo"
done < <(paru -Qe | awk '{print $1}')
